/** Constants exposed only by optional WebGL 2 extensions. */

export const UNMASKED_VENDOR_WEBGL = 0x9245;
export const UNMASKED_RENDERER_WEBGL = 0x9246;

export const MAX_TEXTURE_MAX_ANISOTROPY_EXT = 0x84ff;
export const TEXTURE_MAX_ANISOTROPY_EXT = 0x84fe;

export const COMPRESSED_RGB_S3TC_DXT1_EXT = 0x83f0;
export const COMPRESSED_RGBA_S3TC_DXT1_EXT = 0x83f1;
export const COMPRESSED_RGBA_S3TC_DXT3_EXT = 0x83f2;
export const COMPRESSED_RGBA_S3TC_DXT5_EXT = 0x83f3;

export const COMPRESSED_RGB_PVRTC_4BPPV1_IMG = 0x8c00;
export const COMPRESSED_RGB_PVRTC_2BPPV1_IMG = 0x8c01;
export const COMPRESSED_RGBA_PVRTC_4BPPV1_IMG = 0x8c02;
export const COMPRESSED_RGBA_PVRTC_2BPPV1_IMG = 0x8c03;

export const COMPRESSED_RGB_ETC1_WEBGL = 0x8d64;
export const COMPRESSED_RGB_ATC_WEBGL = 0x8c92;
export const COMPRESSED_RGBA_ATC_EXPLICIT_ALPHA_WEBGL = 0x8c93;
export const COMPRESSED_RGBA_ATC_INTERPOLATED_ALPHA_WEBGL = 0x87ee;

export const QUERY_COUNTER_BITS_EXT = 0x8864;
export const CURRENT_QUERY_EXT = 0x8865;
export const QUERY_RESULT_EXT = 0x8866;
export const QUERY_RESULT_AVAILABLE_EXT = 0x8867;
export const TIME_ELAPSED_EXT = 0x88bf;
export const TIMESTAMP_EXT = 0x8e28;
export const GPU_DISJOINT_EXT = 0x8fbb;
