/** Stable vertex-attribute semantics understood by the shared renderer. */
export const MaterialAttributeSemantic = Object.freeze({
    POSITION: 'POSITION',
    NORMAL: 'NORMAL',
    TANGENT: 'TANGENT',
    TEXCOORD_0: 'TEXCOORD_0',
    TEXCOORD_1: 'TEXCOORD_1',
    COLOR_0: 'COLOR_0',
    SKIN_INDICES: 'SKININDICES',
    SKIN_WEIGHTS: 'SKINWEIGHTS'
} as const);

/** Stable non-texture uniform semantics understood by the shared renderer. */
export const MaterialUniformSemantic = Object.freeze({
    LOCAL: 'LOCAL',
    MODEL: 'MODEL',
    OBJECT_ID_COLOR: 'OBJECTIDCOLOR',
    VIEW: 'VIEW',
    PROJECTION: 'PROJECTION',
    VIEW_PROJECTION: 'VIEWPROJECTION',
    MODEL_VIEW: 'MODELVIEW',
    MODEL_VIEW_PROJECTION: 'MODELVIEWPROJECTION',
    MODEL_INVERSE: 'MODELINVERSE',
    VIEW_INVERSE: 'VIEWINVERSE',
    VIEW_INVERSE_NORMAL: 'VIEWINVERSEINVERSETRANSPOSE',
    PROJECTION_INVERSE: 'PROJECTIONINVERSE',
    MODEL_VIEW_INVERSE: 'MODELVIEWINVERSE',
    MODEL_VIEW_PROJECTION_INVERSE: 'MODELVIEWPROJECTIONINVERSE',
    MODEL_NORMAL: 'MODELINVERSETRANSPOSE',
    MODEL_VIEW_NORMAL: 'MODELVIEWINVERSETRANSPOSE',
    VIEWPORT: 'VIEWPORT',
    CAMERA_FAR: 'CAMERAFAR',
    CAMERA_NEAR: 'CAMERANEAR',
    CAMERA_TYPE: 'CAMERATYPE',
    CAMERA_POSITION: 'CAMERAPOSITION',
    RENDERER_SIZE: 'RENDERERSIZE',
    JOINT_MATRIX: 'JOINTMATRIX',
    NORMAL_MAP_SCALE: 'NORMALMAPSCALE',
    DIFFUSE_COLOR: 'DIFFUSE',
    SPECULAR_COLOR: 'SPECULAR',
    AMBIENT_COLOR: 'AMBIENT',
    EMISSION_COLOR: 'EMISSION',
    OPACITY: 'TRANSPARENCY',
    OCCLUSION_STRENGTH: 'OCCLUSIONSTRENGTH',
    SHININESS: 'SHININESS',
    SPECULAR_ENV_MATRIX: 'SPECULARENVMATRIX',
    REFLECTIVITY: 'REFLECTIVITY',
    REFRACT_RATIO: 'REFRACTRATIO',
    REFRACTIVITY: 'REFRACTIVITY',
    LOG_DEPTH: 'LOGDEPTH',
    AMBIENT_LIGHTS_COLOR: 'AMBIENTLIGHTSCOLOR',
    DIRECTIONAL_LIGHTS_COLOR: 'DIRECTIONALLIGHTSCOLOR',
    DIRECTIONAL_LIGHTS_INFO: 'DIRECTIONALLIGHTSINFO',
    DIRECTIONAL_LIGHTS_SHADOW_MAP_SIZE: 'DIRECTIONALLIGHTSSHADOWMAPSIZE',
    DIRECTIONAL_LIGHTS_SHADOW_BIAS: 'DIRECTIONALLIGHTSSHADOWBIAS',
    DIRECTIONAL_LIGHT_SPACE_MATRIX: 'DIRECTIONALLIGHTSPACEMATRIX',
    DIRECTIONAL_CASCADE_SPLITS: 'DIRECTIONALCASCADESPLITS',
    DIRECTIONAL_CASCADE_PARAMS: 'DIRECTIONALCASCADEPARAMS',
    DIRECTIONAL_CASCADE_MATRICES: 'DIRECTIONALCASCADEMATRICES',
    POINT_LIGHTS_POSITION: 'POINTLIGHTSPOS',
    POINT_LIGHTS_COLOR: 'POINTLIGHTSCOLOR',
    POINT_LIGHTS_INFO: 'POINTLIGHTSINFO',
    POINT_LIGHTS_RANGE: 'POINTLIGHTSRANGE',
    POINT_LIGHTS_SHADOW_BIAS: 'POINTLIGHTSSHADOWBIAS',
    POINT_LIGHT_SPACE_MATRIX: 'POINTLIGHTSPACEMATRIX',
    POINT_LIGHT_CAMERA: 'POINTLIGHTCAMERA',
    SPOT_LIGHTS_POSITION: 'SPOTLIGHTSPOS',
    SPOT_LIGHTS_DIRECTION: 'SPOTLIGHTSDIR',
    SPOT_LIGHTS_COLOR: 'SPOTLIGHTSCOLOR',
    SPOT_LIGHTS_CUTOFFS: 'SPOTLIGHTSCUTOFFS',
    SPOT_LIGHTS_INFO: 'SPOTLIGHTSINFO',
    SPOT_LIGHTS_RANGE: 'SPOTLIGHTSRANGE',
    SPOT_LIGHTS_SHADOW_MAP_SIZE: 'SPOTLIGHTSSHADOWMAPSIZE',
    SPOT_LIGHTS_SHADOW_BIAS: 'SPOTLIGHTSSHADOWBIAS',
    SPOT_LIGHT_SPACE_MATRIX: 'SPOTLIGHTSPACEMATRIX',
    AREA_LIGHTS_POSITION: 'AREALIGHTSPOS',
    AREA_LIGHTS_COLOR: 'AREALIGHTSCOLOR',
    AREA_LIGHTS_WIDTH: 'AREALIGHTSWIDTH',
    AREA_LIGHTS_HEIGHT: 'AREALIGHTSHEIGHT',
    FOG_COLOR: 'FOGCOLOR',
    FOG_INFO: 'FOGINFO',
    SHADOW_ATLAS_SIZE: 'SHADOWATLASSIZE',
    SHADOW_ATLAS_RECTS: 'SHADOWATLASRECTS',
    POINT_SHADOW_MATRICES: 'POINTSHADOWMATRICES',
    POSITION_DECODE_MATRIX: 'POSITIONDECODEMAT',
    NORMAL_DECODE_MATRIX: 'NORMALDECODEMAT',
    UV_DECODE_MATRIX: 'UVDECODEMAT',
    UV1_DECODE_MATRIX: 'UV1DECODEMAT',
    BASE_COLOR: 'BASECOLOR',
    EMISSION_FACTOR: 'EMISSIONFACTOR',
    METALLIC: 'METALLIC',
    ROUGHNESS: 'ROUGHNESS',
    DIFFUSE_ENV_INTENSITY: 'DIFFUSEENVINTENSITY',
    SPECULAR_ENV_INTENSITY: 'SPECULARENVINTENSITY',
    SPECULAR_ENV_MIP_COUNT: 'SPECULARENVMAPMIPCOUNT',
    DIFFUSE_ENV_SPHERICAL_HARMONICS: 'DIFFUSEENVSPHEREHARMONICS3',
    GLOSSINESS: 'GLOSSINESS',
    ALPHA_CUTOFF: 'ALPHACUTOFF',
    TEMPORAL_REACTIVE_FACTOR: 'TEMPORALREACTIVEFACTOR',
    MORPH_WEIGHTS: 'MORPHWEIGHTS',
    CLEARCOAT_FACTOR: 'CLEARCOATFACTOR',
    CLEARCOAT_ROUGHNESS_FACTOR: 'CLEARCOATROUGHNESSFACTOR',
    CLEARCOAT_NORMAL_SCALE: 'CLEARCOATNORMALSCALE',
    ANISOTROPY_STRENGTH: 'ANISOTROPYSTRENGTH',
    ANISOTROPY_ROTATION: 'ANISOTROPYROTATION',
    TRANSMISSION_FACTOR: 'TRANSMISSIONFACTOR',
    THICKNESS_FACTOR: 'THICKNESSFACTOR',
    ATTENUATION_DISTANCE: 'ATTENUATIONDISTANCE',
    ATTENUATION_COLOR: 'ATTENUATIONCOLOR',
    IOR: 'IOR',
    IRIDESCENCE_FACTOR: 'IRIDESCENCEFACTOR',
    IRIDESCENCE_IOR: 'IRIDESCENCEIOR',
    IRIDESCENCE_THICKNESS_MINIMUM: 'IRIDESCENCETHICKNESSMINIMUM',
    IRIDESCENCE_THICKNESS_MAXIMUM: 'IRIDESCENCETHICKNESSMAXIMUM',
    MATERIAL_TEXTURE_TRANSFORMS: 'MATERIALTEXTURETRANSFORMS',
    MATERIAL_TEXTURE_INFO: 'MATERIALTEXTUREINFO',
    MATERIAL_TEXTURE_CHANNELS: 'MATERIALTEXTURECHANNELS'
} as const);

/** Stable sampled-resource semantics understood by the shared renderer. */
export const MaterialTextureSemantic = Object.freeze({
    SHADOW_ATLAS: 'SHADOWATLAS',
    DIRECTIONAL_LIGHTS_SHADOW_MAP: 'DIRECTIONALLIGHTSSHADOWMAP',
    POINT_LIGHTS_SHADOW_MAP: 'POINTLIGHTSSHADOWMAP',
    SPOT_LIGHTS_SHADOW_MAP: 'SPOTLIGHTSSHADOWMAP',
    AREA_LIGHTS_LTC_TEXTURE_1: 'AREALIGHTSLTCTEXTURE1',
    AREA_LIGHTS_LTC_TEXTURE_2: 'AREALIGHTSLTCTEXTURE2',
    DIFFUSE: 'DIFFUSE',
    SPECULAR: 'SPECULAR',
    EMISSION: 'EMISSION',
    AMBIENT: 'AMBIENT',
    NORMAL_MAP: 'NORMALMAP',
    PARALLAX_MAP: 'PARALLAXMAP',
    OPACITY: 'TRANSPARENCY',
    BASE_COLOR_MAP: 'BASECOLORMAP',
    METALLIC_MAP: 'METALLICMAP',
    ROUGHNESS_MAP: 'ROUGHNESSMAP',
    METALLIC_ROUGHNESS_MAP: 'METALLICROUGHNESSMAP',
    OCCLUSION_MAP: 'OCCLUSIONMAP',
    SPECULAR_GLOSSINESS_MAP: 'SPECULARGLOSSINESSMAP',
    LIGHT_MAP: 'LIGHTMAP',
    CLEARCOAT_MAP: 'CLEARCOATMAP',
    CLEARCOAT_ROUGHNESS_MAP: 'CLEARCOATROUGHNESSMAP',
    CLEARCOAT_NORMAL_MAP: 'CLEARCOATNORMALMAP',
    ANISOTROPY_MAP: 'ANISOTROPYMAP',
    TRANSMISSION_MAP: 'TRANSMISSIONMAP',
    THICKNESS_MAP: 'THICKNESSMAP',
    IRIDESCENCE_MAP: 'IRIDESCENCEMAP',
    IRIDESCENCE_THICKNESS_MAP: 'IRIDESCENCETHICKNESSMAP',
    DIFFUSE_ENV_MAP: 'DIFFUSEENVMAP',
    BRDF_LUT: 'BRDFLUT',
    SPECULAR_ENV_MAP: 'SPECULARENVMAP',
    OPAQUE_SCENE_TEXTURE: 'OPAQUETEXTURE',
    /** Pass-global ground-truth ambient visibility texture. */
    GROUND_TRUTH_AMBIENT_OCCLUSION: 'GTAOTEXTURE'
} as const);

export type MaterialAttributeSemanticName =
    | (typeof MaterialAttributeSemantic)[keyof typeof MaterialAttributeSemantic]
    | `MORPH${'POSITION' | 'NORMAL' | 'TANGENT'}${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7}`;

export type MaterialUniformSemanticName =
    (typeof MaterialUniformSemantic)[keyof typeof MaterialUniformSemantic];
export type MaterialTextureSemanticName =
    | (typeof MaterialTextureSemantic)[keyof typeof MaterialTextureSemantic]
    | `${'DIFFUSE' | 'SPECULAR' | 'EMISSION' | 'AMBIENT'}UV`
    | `${
          | 'NORMALMAP'
          | 'PARALLAXMAP'
          | 'BASECOLORMAP'
          | 'METALLICMAP'
          | 'ROUGHNESSMAP'
          | 'METALLICROUGHNESSMAP'
          | 'OCCLUSIONMAP'
          | 'SPECULARGLOSSINESSMAP'
          | 'LIGHTMAP'
          | 'CLEARCOATMAP'
          | 'CLEARCOATROUGHNESSMAP'
          | 'CLEARCOATNORMALMAP'
          | 'ANISOTROPYMAP'
          | 'TRANSMISSIONMAP'
          | 'THICKNESSMAP'
          | 'IRIDESCENCEMAP'
          | 'IRIDESCENCETHICKNESSMAP'}UV`
    | 'TRANSPARENCYUV';

/** Any built-in semantic identifier accepted by a string material binding. */
export type MaterialSemanticName =
    MaterialAttributeSemanticName | MaterialUniformSemanticName | MaterialTextureSemanticName;
