name: npm test

on:
  push:
    branches: [ dev, master, test ]
  pull_request:
    branches: [ dev ]

jobs:
  test:

    runs-on: macos-12

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: npm test
      run: |
        npm test
      env:
        CI: true
